[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#4A1525"
backgroundColor = "#FDFBF7"
secondaryBackgroundColor = "#F4EDE2"
textColor = "#1F070E"
font = "sans serif"
